name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          registry-url: https://registry.npmjs.org/
      - run: bun install --frozen-lockfile
      - run: bun run build
      - run: bun publish
        env:
          BUN_AUTH_TOKEN: ${{secrets.npm_token}}
